name: PR - Build Pipeline
run-name: "PR - ${{ github.event.repository.name }} Build #${{ github.run_number }}"

on:
  pull_request:
    branches: main
  push:
    branches: features/ci-build


concurrency:
  group: build-pr-${{ github.event.pull_request.number }}
  # If this is enabled it will cancel current running and start latest
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/template-build.yml
    with:
      upload-artifact: false
      app-solution: './CashFlow.sln'
      app-publish-project: './src/Presentation/WebApi/CashFlow.Presentation.WebApi.csproj'